{
  "question_id" : 44806088,
  "title" : "HostingEnvironment caused shutdown Umbraco",
  "body" : "<p>I am getting an old issue of umbraco: [<a href=\"https://our.umbraco.org/forum/getting-started/installing-umbraco/72398-hostingenvironment-initiated-shutdown]\" rel=\"nofollow noreferrer\">https://our.umbraco.org/forum/getting-started/installing-umbraco/72398-hostingenvironment-initiated-shutdown]</a></p>\n\n<p>I get this issue when I am trying to Install Umbraco, it all goes smooth but in the end it says that it occured an Error please check Logs folder when I check it this is the message <code>HostingEnvironment caused shutdown</code> though it seems, it does install Umbraco and the Fanoe starterkit and when I try to access \"mywebsite/umbraco\" (<a href=\"https://imgur.com/a/eSCJW\" rel=\"nofollow noreferrer\">http://imgur.com/a/eSCJW</a>) and put my login credentials that I created at the start of the wizard it just stays a blank page.</p>\n\n<p>If I am not mistaken there was a hotfix from Microsoft but only for Windows Server 2012 R2 and Windows 8.1.</p>\n\n<p>The problem is that I am getting this error on a Virtual Machine in Azure with Windows Server 2016 Datacenter.</p>\n\n<p>Thanks in advance. </p>\n\n<p>Here is part of my log:</p>\n\n<pre><code>     _shutDownMessage=CONFIG change\n        HostingEnvironment initiated shutdown\n        CONFIG change\n        HostingEnvironment caused shutdown\n\n        _shutDownStack=   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)\n           at System.Environment.get_StackTrace()\n           at System.Web.Hosting.HostingEnvironment.InitiateShutdownInternal()\n           at \n\nSystem.Web.Hosting.HostingEnvironment.InitiateShutdownWithoutDemand()\n       at System.Web.HttpRuntime.ShutdownAppDomain(String stackTrace)\n       at System.Web.Configuration.HttpConfigurationSystem.OnConfigurationChanged(Object sender, InternalConfigEventArgs e)\n       at System.Configuration.Internal.InternalConfigRoot.OnConfigChanged(InternalConfigEventArgs e)\n       at System.Configuration.BaseConfigurationRecord.OnStreamChanged(String streamname)\n       at System.Web.DirectoryMonitor.FireNotifications()\n       at System.Web.Util.WorkItem.CallCallbackWithAssert(WorkItemCallback callback)\n       at System.Web.Util.WorkItem.OnQueueUserWorkItemCompletion(Object state)\n       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)\n       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)\n       at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()\n       at System.Threading.ThreadPoolWorkQueue.Dispatch()\n     2017-06-28 11:03:53,043 [P4468/D12/T37] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable\n     2017-06-28 11:03:53,043 [P4468/D12/T37] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)\n     2017-06-28 11:03:53,044 [P4468/D12/T37] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IAction\n     2017-06-28 11:03:53,046 [P4468/D12/T37] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IAction (took 2ms)\n     2017-06-28 11:04:06,381 [P4468/D12/T14] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable\n     2017-06-28 11:04:06,382 [P4468/D12/T14] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 1ms)\n     2017-06-28 11:04:06,383 [P4468/D12/T14] INFO  Umbraco.Core.PluginManager - Resolving [Umbraco.Core.Persistence.Mappers.MapperForAttribute]Umbraco.Core.Persistence.Mappers.BaseMapper\n     2017-06-28 11:04:06,388 [P4468/D12/T14] INFO  Umbraco.Core.PluginManager - Resolved [Umbraco.Core.Persistence.Mappers.MapperForAttribute]Umbraco.Core.Persistence.Mappers.BaseMapper (took 5ms)\n     2017-06-28 11:04:06,652 [P4468/D12/T14] INFO  Umbraco.Core.Security.BackOfficeSignInManager - Event Id: 0, state: Login attempt failed for username admin from IP address 127.0.0.1\n     2017-06-28 11:04:17,777 [P4468/D12/T38] INFO  Umbraco.Core.Security.BackOfficeSignInManager - Event Id: 0, state: Login attempt succeeded for username admin@admin.admin from IP address 127.0.0.1\n     2017-06-28 11:04:17,778 [P4468/D12/T38] INFO  Umbraco.Core.Security.BackOfficeSignInManager - Event Id: 0, state: User: admin@admin.admin logged in from IP address 127.0.0.1\n     2017-06-28 11:04:19,797 [P4468/D12/T9] INFO  umbraco.BusinessLogic.Log - Log scrubbed.  Removed all items older than 2017-06-27 11:04:19\n     2017-06-28 11:04:53,341 [P4468/D12/T35] WARN  Umbraco.Web.UmbracoModule - Status code is 404 yet TrySkipIisCustomErrors is false - IIS will take over.\n</code></pre>\n",
  "link" : "https://stackoverflow.com/questions/44806088/hostingenvironment-caused-shutdown-umbraco",
  "owner" : {
    "user_id" : 7604065,
    "user_type" : "registered",
    "display_name" : "Samuel Silva",
    "profile_image" : "https://www.gravatar.com/avatar/32b9da010272c0dae516f64a56fc4271?s=128&d=identicon&r=PG&f=1",
    "link" : "https://stackoverflow.com/users/7604065/samuel-silva",
    "reputation" : 25,
    "accept_rate" : 100
  },
  "is_answered" : false,
  "creation_date" : 1498661863,
  "last_activity_date" : 1498661863,
  "tags" : [
    "azure",
    "virtual-machine",
    "umbraco",
    "umbraco7",
    "windows-server-2016"
  ],
  "score" : 0,
  "view_count" : 4,
  "answer_count" : 0
}